Redux thunk
Ruymelo10/squad-builder-react pull request #4
Opened 2021-07-27 04:47 UTC by Ruymelo10

adding redux thunk to the application for fetching users from json-server

2021-07-27 15:00 UTC, JonasMazza requested changes

2021-07-27 15:00 UTC, JonasMazza commented on src/container/fetchUser/fetchUserReducer.js
> +        ...action.payload,
não deveria ser assim?
```
return {
  ...state,
  users: action.payload,
  status: 'fetch-success',
  error: null,
}
```

2021-07-27 16:32 UTC, Ruymelo10 commented on src/container/fetchUser/fetchUserReducer.js
> +        ...action.payload,
É isso mesmo. vou alterar

2021-08-16 17:21 UTC, JonasMazza approved these changes

2021-08-16 17:22 UTC, merged